language: ruby

cache: bundler

bundler_args: "--binstubs --path ../bundle --retry=3 --jobs=3"

before_install:
  - yes | gem update --system --force
  - gem install bundler

env:
 - RAILS_VERSION='~> 5.2'
 - RAILS_VERSION='~> 6.0'

rvm:
  - 2.6
  - 2.7
